### ISSUE TITLE
Free editor.slf releases

### ISSUE THREAD

**Issue by flaviojs** [ja2-stracciatella/free-ja2-resources#5]
How about starting to make releases of the free editor.slf?

It could also be a mod in `ja2-stracciatella`, but I'm not too keen on that.

**Comment by lynxlynxlynx** [comment]
I agree that it should not be a mod in the -mod sense. The launcher and switch are there by default, so it should just work. So for ease of use, I'd bundle it with ja2 (on release), whether it has it's own releases or not.

**Comment by selaux** [comment]
Same for me. Although for now I would have it as a lower priority than the original one, as the free one does not contain all graphics yet...

**Comment by flaviojs** [comment]
Since #3 was merged, the free `editor.slf` contains all the graphics that the editor uses.
They are mostly simple buttons with some text.
The required files are listed in [`editor/README.md`](https://github.com/ja2-stracciatella/free-ja2-resources/blob/master/editor/README.md).

Currently only `(game_dir)/data/*.slf` are loaded and slfs have lower priority than raw files.
Adding the free `editor.slf` after those slfs would be sufficient to get a lower priority.
Now the question is, where should the free `editor.slf` be placed?

I vote for `(assets_dir)/editor.slf` because it does not follow the usual data dir ordering.
(`(assets_dir)` is where the `mods` and `externalized` dirs were installed to)

**Comment by lynxlynxlynx** [comment]
Sounds fine.

**Comment by flaviojs** [comment]
Ok, then the last question is how to bundle `editor.slf` with `ja2-stracciatella`.

I see 4 alternatives:

1) build `editor.slf` during the normal build process.
  This means extra dependencies at build time.

2) download from a url pointing to a specific `editor.slf` release.
  To avoid downloading the editor again in rebuilds, cmake would compare the md5 checksum of the local version. `CMakeLists.txt` would need to be updated on every `editor.slf` release.

3) download from a url pointing to the latest `editor.slf` release.
  To avoid downloading the editor again in rebuilds, cmake would get the md5 from a similar url and compare it with the md5 checksum of the local version. The content of the "latest" urls would need to be updated on every `editor.slf` release.

4) commit `editor.slf` in the `ja2-stracciatella` repo.
  Increases the repo size by ~565kb on every `editor.slf` release.

I vote for 2) or 3). =~

**Comment by lynxlynxlynx** [comment]
I'd go for 3., but only in "make dist" or whatever we use to make proper releases. I don't think we need to bother having it around all the time.

**Comment by flaviojs** [comment]
Github has a url to get the assets of the latest release:
https://developer.github.com/v3/repos/releases/#get-the-latest-release

The response is in json, which cmake does not read natively.
Fortunately someone already implemented a module for that:
https://github.com/sbellus/json-cmake

To make a release I need to create a tag.
What do you think of using `v1.<utc date of commit>`?

It's not really semantic versioning but it's fully compatible.
If there are multiple releases in the same date the patch version can be incremented: `v1.<date>.1`
If a new file starts being required the major version can be incremented: `v2.<date>`

**Comment by lynxlynxlynx** [comment]
I'd just go with vN or N, no suffix — less hassle.

**Comment by flaviojs** [comment]
The release v1 was made and ja2-stracciatella includes the latest one in release builds.
